### PR TITLE
Adding text about non-discrimination

### PR DESCRIPTION
**Pull request by agentolivia**
I think it's important to be explicit in our core values that we do not discriminate as we empower our team members with opportunities for growth. I feel this is assumed by all of us and in practice, and it should be explicitly stated somewhere in our values. I think often workplaces find excuses or put up barriers for people based on various things. Some of these things are protected classes in the United States of America, and some are common excuses for actively preventing someone from growing or being promoted within the company. I think we are a very flexible and empowering company and even though this is a negative statement (as in what we do NOT do), I think it's important to state clearly in our core values.

Not sure about the precise wording in certain cases and I welcome edits and discussion about this proposed change.

### CODE REVIEW

**Comment by add1sun** [comment]
I like the idea of adding this in the values section. I think we can simplify the text here and then link to the full Diversity and Inclusion statement (https://github.com/OsioLabs/emphandbook/blob/master/04emp_conduct/02diversity.md).

**Comment by agentolivia** [comment]
@add1sun Rephrased and linked to D&I page. (Good idea!)

**Comment by add1sun** [comment]
That looks good to me. If no one else has any comments early next week, I'll go ahead and merge it in then.

**Comment by eojthebrave** [comment]
👍

**Pull request merged**
