### PR TITLE
Add open source to our vision

### LINKED ISSUE #16: Update vision to include open source
From the 2019 Sedona retreat.

We would like to make sure that our vision reflects our desire to support and grow open source. It currently is reflected in our values, but not in the vision itself.

### PR DESCRIPTION
**Pull request by add1sun**
Resolves #16

### CODE REVIEW

**Comment by add1sun** [comment]
@eojthebrave @blakehall @agentolivia @ashleyrian @philippa5 Does this change capture open source well enough int he vision?

**Comment by blakehall** [comment]
This looks good to me 👍

**Comment by eojthebrave** [comment]
❤️

**Comment by agentolivia** [comment]
+1

**Pull request merged**
